name: Build Android APK

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'

      # Uses Gradle’s official action (handles caching & wrapper nicely)
      - name: Prepare Gradle
        uses: gradle/actions/setup-gradle@v3

      # If your project is NOT at repo root, set working-directory below to that folder
      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Build debug APK
        run: ./gradlew assembleDebug

      - name: Collect APKs
        run: |
          mkdir -p apks
          # copy any produced APKs into apks/
          find . -path "*/build/outputs/apk/*/*.apk" -exec cp {} apks/ \; || true

      - name: Upload APKs
        uses: actions/upload-artifact@v4
        with:
          name: android-apks
          path: apks/*
