name: Hello
on:
  workflow_dispatch:

jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout (ok if empty)
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "17"

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: stable
          channel: stable

      - name: Create a sample Flutter app (so we can build)
        run: flutter create clearpix_ai

      - name: Get packages
        working-directory: clearpix_ai
        run: flutter pub get

      - name: Build APK (release)
        working-directory: clearpix_ai
        run: flutter build apk --release

      - name: Upload APK artifact
        uses: actions/upload-artifact@v4
        with:
          name: clearpix-ai-apk
          path: clearpix_ai/build/app/outputs/flutter-apk/app-release.apk
