- name: Add app code (UI + Ads + Save gate)
      working-directory: clearpix_ai
      shell: bash
      run: |
        mkdir -p lib/ui lib/ads lib/services
        
        cat > lib/main.dart <<'DART'
        import 'package:flutter/material.dart';
        import 'package:google_mobile_ads/google_mobile_ads.dart';
        import 'ads/ad_manager.dart';
        import 'services/save_gate.dart';
        import 'ui/home.dart';

        void main() async {
          WidgetsFlutterBinding.ensureInitialized();
          await MobileAds.instance.initialize();
          runApp(ClearPixApp());
        }

        class ClearPixApp extends StatelessWidget {
          @override
          Widget build(BuildContext context) => MaterialApp(
            title: 'ClearPix AI',
            theme: ThemeData(useMaterial3: true, colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue)),
            darkTheme: ThemeData(useMaterial3: true, brightness: Brightness.dark, colorScheme: ColorScheme.fromSeed(seedColor: Colors.blue)),
            home: HomeScreen(),
            debugShowCheckedModeBanner: false,
          );
        }
        DART
